const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const {webcrypto}=require('node:crypto');
function element(extra={}){return {value:'',dataset:{},disabled:false,textContent:'',innerHTML:'',options:[],classList:{add(){},remove(){},toggle(){},contains(){return true;}},setAttribute(){},removeAttribute(){},querySelector(){return null},querySelectorAll(){return []},...extra};}
function context(file,sb){const elements=new Map(),memory=new Map();const document={documentElement:{lang:'ar'},querySelector:s=>elements.get(s)||null,querySelectorAll:()=>[],addEventListener(){},createElement:()=>element(),body:{append(){},classList:{toggle(){}}}};const ctx={document,window:{NADIA_SUPABASE:{url:'https://example.test',anonKey:'public-test'},supabase:{createClient:()=>sb},scrollTo(){}},supabase:{createClient:()=>sb},localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)},console,crypto:webcrypto,TextEncoder,URL,URLSearchParams,location:{pathname:'/checkout.html',href:'https://example.test/checkout.html',search:''},setTimeout:()=>0,clearTimeout(){},FormData:class{constructor(form){this.values=form.values||{};}get(k){return this.values[k]??null;}},lang:'ar',t:(ar,en)=>ar,alert(){},confirm:()=>true};vm.createContext(ctx);vm.runInContext(fs.readFileSync('store-core.js','utf8'),ctx);vm.runInContext(fs.readFileSync(file,'utf8'),ctx);return {ctx,elements,run:s=>vm.runInContext(s,ctx)};}
(async()=>{
 const ui=context('app.js',{rpc:async()=>{throw Error('Network offline')}});
 let el=element({dataset:{ar:'قديم',en:'Old'},textContent:'Old'});ui.ctx.testElement=el;ui.run("applyCmsText(testElement,'','')");assert.equal(el.textContent,'');
 el=element({hidden:false});ui.ctx.testElement=el;ui.run("applyCmsImage(testElement,'')");assert.equal(el.hidden,true);
 const btn=element(),country=element({value:'EG'});ui.elements.set('#checkoutCountry',country);ui.elements.set('#checkoutForm [type=submit]',btn);ui.elements.set('#orderSummary',element());
 ui.run("allProducts=[{id:'00000000-0000-4000-8000-000000000000',slug:'test',name_ar:'اختبار',price:100,stock:3,active:true}];productsLoaded=true;cart=[{slug:'test',qty:1}];window.NADIA_CMS_SETTINGS={currency:'EGP',checkout_enabled:true,policies_ready:true,payment_method:'manual',shipping_rates:[{country:'EG',fee:25}]};");
 ui.ctx.event={preventDefault(){},target:{values:{customer_name:'Test',phone:'00000000000',terms_accepted:'on'},querySelector:()=>btn}};
 await ui.run('submitOrder(event)');assert.equal(btn.disabled,false);assert.equal(btn.dataset.sending,undefined);assert.equal(ui.run('cart.length'),1);
 const admin=context('admin.js',{from(){return {select(){return this},order(){return this},range:async()=>({error:{message:'offline'}})}}});
 const body=element();admin.elements.set('#ordersBody',body);await admin.run('loadOrders()');assert.match(body.innerHTML,/تعذر تحميل الطلبات/);assert(!body.innerHTML.includes('لا توجد طلبات'));
 const form=element({reset(){this.resetCalled=true;}});admin.elements.set('#productForm',form);admin.elements.set('[name="active"]',element());admin.elements.set('[name="featured"]',element());admin.elements.set('#productEditor',element());
 admin.run("products=[{id:'test',updated_at:'version',active:true,featured:false}];editProduct('test')");assert.equal(form.resetCalled,true);assert.equal(admin.run('editingVersion'),'version');
 console.log('PASS: blank CMS edits, cleared images, network retry button, preserved cart, explicit admin load errors, product form reset');
})().catch(e=>{console.error(e);process.exitCode=1;});
